### ISSUE TITLE
Improve `Private pods` 

### ISSUE THREAD

**Issue by mattmorton** [CocoaPods/guides.cocoapods.org#69]
Also see https://github.com/CocoaPods/guides.cocoapods.org/issues/28

The  [Private Pods](https://guides.cocoapods.org/making/private-cocoapods.html) page is a little unclear in it's explanation of how to go about creating a private spec repo and adding Podspec files.

Part 1, Create a private spec repo, should be clearer about creating a repo, simply requiring an empty repo.  Adding a Podspec is also more straightforward than it appears, simply creating the Podspec file and running the pod repo push command.

Ultimately, the structure description is misguiding.

**Comment by AliSoftware** [comment]
Could you maybe try to do a Pull Request?
CP Guides are quite easy to contribute to (see `CONTRIBUTING.md`) and we would love to have an external point of view on how the guides should better explain it (it's not always easy, when you work on it a lot and know how things work, to see what's trivial and how things should be better explained), so that would help a lot!

Thanks!

**Comment by mattmorton** [comment]
Sure, I've started already. Hopefully be able to come up with something helpful. Cheers Oliver.

**Comment by AliSoftware** [comment]
Cool :+1:

**Comment by orta** [comment]
great job.
